development:
  adapter: postgresql
  database: helpfrog_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: helpfrog_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: helpfrog
  pool: 5
  timeout: 5000